name: DEUXIEME ARTEFACT
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v3

      - name: install cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }} - ${{hashFiles('./vite-project/package-lock.json')}}
          path: ./vite-project/.npm

      - name: install dependences
        working-directory: ./vite-project
        run: npm ci --cache .npm --prefer-offline

      - name: Build application
        working-directory: ./vite-project
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build_artefact
          path: ./vite-project/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build_artefact
          path: ./build
      - run: |
          ls
          ls build
