name: CI-CD pour nodejs
on:
  push:
    branches-ignore:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: npm install dépendance
        run: npm install

      - name: éxecute des tests
        run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && success() }}
    steps:
      - name: déploiement sur serveur de production
        run: ./deploy.sh
