name: Exemple de CI avec conteneur
on:
  push:
    branches: [dev]
jobs:
  exemple-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: vérifie l'existence du fichier .dockerenv
        run: (ls /.dockerenv && echo "fichier .dockerenv trouvé") || echo "fichier .dockerenv absent"
