name: install package
on: [pull_request]
defaults:
  run:
    shell: bash
    working-directory: ./vite-project

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: fetch checkout
        uses: actions/checkout@v4
      - name: install dependences project
        run: npm install
