name: Exemple d'extension de configurations

on:
  push:
    branches:
      - dev

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
        include:
          - os: windows-latest
            node: 16
            npm: 6
    runs-on: ${{ matrix.os }}
    steps:
      - name: Affichage des variables de la matrice
        run: |
          echo "OS : ${{ matrix.os }}"
          echo "Node : ${{ matrix.node }}"
          if [ "${{ matrix.npm }}" != "" ]; then
            echo "NPM : ${{ matrix.npm }}"
          fi
